### ISSUE TITLE
`scroll-chan` does not work with older Elasticsearch versions

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [mpenet/spandex#12]
I was trying to use `scroll-chan` on ES 1.4, but I only got the first page. It looked like the pagination was not working, therefore I looked at what spandex does. It turns out, the way ES 1.4 scrolls is, instead of specifying a body JSON object but takes a `scroll-id` directly. [See the ES docs here](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-request-scroll.html). According to the ES docs [this was changed in 2.0](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-scroll.html#scroll-scan).

But these approaches can be reconciliated:

> For backwards compatibility, scroll_id and scroll can be passed in the query string. And the scroll_id can be passed in the request body

I would propose doing exactly this, which would make spandex scrolling be compatible with ES < 2.0.

**Comment by mpenet** [comment]
"ES 1.4", I feel your pain :) 

Sounds good to me, feel free to submit a PR for this, happy to merge it.

**Comment by Leonidas-from-XIV** [comment]
Yeah, there are a number of quirks with ES 1.4, so I took care of this particular one in #13 :)

**Comment by mpenet** [comment]
It seems to be broken on 5.4.x :(

**Comment by mpenet** [comment]
I think it's fixable by passing the scroll_id in the query-string

**Comment by Leonidas-from-XIV** [comment]
Both in body and query string?
