### ISSUE TITLE
Bulk API never closes the output channel

### ISSUE THREAD

**Issue by rauhs** [mpenet/spandex#17]
I'm trying to use the bulk API. It works pretty great (100k document in ~10second) :).

Not sure if I'm using it incorrectly but I'm listening on the output channel and I can't exit the go-loop since the output channel is never closed. I see the request channel is closed when the input channel is closed.

Is this is a bug or should I exit and cleanup myself and checking the request channel?

**Comment by mpenet** [comment]
Glad it's working for you :) 
I will add closing of the output channel once all pending requests have been processed; it's not something I had a use for but it makes sense to do it.

**Comment by mpenet** [comment]
available in 0.3.10
