### ISSUE TITLE
When to instantiate the client

### ISSUE THREAD

**Issue by DonDebonair** [mpenet/spandex#18]
According to the [ES Java client documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html) you can/should create only one client for your application, and reuse it across your app. The example code suggests this:

```java
// on startup

TransportClient client = new PreBuiltTransportClient(Settings.EMPTY)
        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("host1"), 9300))
        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("host2"), 9300));

// on shutdown

client.close();
```

Seeing that Spandex is based on the official Java client, I assume the same holds here. When and where would you instantiate the client then? I was thinking of `defonce`'ing an atom somewhere, and instantiating the client and binding it to that atom when starting my app in the `main` namespace. Is that the correct way to go? Or do you suggest something else?

**Comment by mpenet** [comment]
I would say it's 1 per cluster you interact with more than "per application". But yes, spandex follows the same rules, then the way you maintain this client is up to you, I personally prefer to use something like "component".

**Comment by DonDebonair** [comment]
If Component is overkill, how would you share this client across your Clojure app?

**Comment by mpenet** [comment]
`(defonce client (delay (es/client {...})))`

**Comment by DonDebonair** [comment]
Thanks for the help!
