### ISSUE TITLE
Code formatting?

### ISSUE THREAD

**Issue by rborer** [mpenet/spandex#2]
I'm used to https://github.com/weavejester/cljfmt to automatically format code the same way for all contributors, if you like the idea I can do a PR to enable the plugin and reformat the existing code base 😃

**Comment by mpenet** [comment]
Sure you can submit a PR. 
I usually just rely on cider defaut indent rules + 80col limit + clj style guide. One thing I'd like to keep this way (maybe) is imports/require formatting, I find it more readable, but I am not sure cljfmt impacts this. (I am on holiday from this morning, I ll be a bit slow).

**Comment by rborer** [comment]
I'll prepare a PR and you can have a look. cljfmt does not touch the imports & requires formatting at all.
