### ISSUE TITLE
How to use the bulk API?

### ISSUE THREAD

**Issue by faxm0dem** [mpenet/spandex#20]
What I tried:

```clojure
(s/request c {:url (s-utils/url [:_bulk]) :method :post :body {:delete {:_index "foo" :_id "1234"}}})
```

This gets me:

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 235

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no requests added;"}],"type":"action_request_validation_exception","reason":"ValidationFailed: 1: no requests added;"},"status":400}
```

Cheers

**Comment by faxm0dem** [comment]
answering to myself, I need to pass through the body formatter first:

```clojure
(s/request c {:url (s-utils/url [:_bulk]) :method :post :body (s/chunks->body [{:delete {:_index "foo" :_type "bar" :_id "1234"}}])})
```

**Comment by mpenet** [comment]
we might add more utils to deal with this in the near future (we were talking about it these past few days)

**Comment by faxm0dem** [comment]
@mpenet can I use multiple connections per ES node using `request` or do I need to open a `bulk-channel` ?

**Comment by mpenet** [comment]
Per client instance you have the following defaults: 
```java
    DEFAULT_CONNECT_TIMEOUT_MILLIS = 1000;
    DEFAULT_SOCKET_TIMEOUT_MILLIS = 30000;
    DEFAULT_MAX_RETRY_TIMEOUT_MILLIS = DEFAULT_SOCKET_TIMEOUT_MILLIS;
    DEFAULT_CONNECTION_REQUEST_TIMEOUT_MILLIS = 500;
    DEFAULT_MAX_CONN_PER_ROUTE = 10;
    DEFAULT_MAX_CONN_TOTAL = 30;
```

And you can alter these values at the client level if you need to. see client options

**Comment by faxm0dem** [comment]
Thanks @mpnet however even if I raise the max per route, I only see one open connection per node (netstat). That being said, I'm very happy with the performance: almost 20'000 events sent per second on 4 nodes (as seen by http response times)

**Comment by mpenet** [comment]
Nice  :) 

That's odd about the connection setting, I am on a trip right now but I ll try to dig into this when I am back.

**Comment by mpenet** [comment]
Just to be sure, you tried with `{:http-client {:max-conn-per-route N}}` right?

**Comment by faxm0dem** [comment]
positive

**Comment by faxm0dem** [comment]
As I switched back to default settings (without `{:max-conn-per-route N}`) I now see 2 connections per node, so I guess it's kind of working :+1:

**Comment by mpenet** [comment]
Back to that one, it can of slipped under my radar. 

That's really odd, it's probably a misunderstanding on how the apache client deals with this.
