### ISSUE TITLE
bulk api index requests

### ISSUE THREAD

**Issue by beoliver** [mpenet/spandex#26]
As the api takes requests of the form:

```
POST _bulk
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_type" : "type1", "_id" : "2" } }
{ "create" : { "_index" : "test", "_type" : "type1", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_type" : "type1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
```
Is there a clean work around to make sure that *pairs* of lines can be merged when putting onto the channel? Of course it is possible to set the `:flush-threshold` to an even number if working with only `create`, `index`, `update` but if there is a mix to be processed then it is quite possible that a request is made
```
POST _bulk
...
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
```
followed by 

```
POST _bulk
{ "field1" : "value1" }
...
```
which obviously introduces errors that really don't need to be there.
Ideally (and I'm not sure if this is possible) it should be possible to create chunks that *need* to be together. Of course this is possible using the normal requests to `_bulk`.

Perhaps we could just put raw strings onto the channel? i.e 
```
(s/raw (str (json/encode <foo>) "\n" (json/encode <bar>) "\n"))
```
or vectors like `[<foo> <bar>]`

**Comment by jmshelby** [comment]
The documentation shows that you can put a sequence of multiple lines on the channel. From looking at the code, it does appear that the :flush-threashold is indeed counting each chunk you put on the channel (I.e pairs, if you put pairs into a sequence). So everything should work the way you expect, just group those into sequences.

Also, this is pretty vital (grouping related lines in a sequence) because there is a flush timeout as well, which could flush before the threshold is met (which is a pretty awesome feature, that I don't think is highlighted well in the documentation)

**Comment by beoliver** [comment]
Thanks for the response! Ok, so I completely missed that in the doc string (and the code comment on the README example) 😊  - I think the timeout option (and default) is clear - it was actually the reason I started worrying. Perhaps the front page bulk example could include an explicit seqence? It would make it super intuitive. i.e is it actually a `seq?`. I will answer my own question, just thinking out loud. Anyway, I guess this can be closed!

**Comment by mpenet** [comment]
I somehow missed that issue. 
But it does work as @jmshelby described (thanks!) and as stated in the documentation. That's a good idea about the example on the readme, feel free to file a PR, otherwise I might do it myself in the next few days.

**Comment by mpenet** [comment]
This makes me think I might add another option for this as a predicate that would trigger the flushing, this would allow users to have their own heuristics and flush on payload absolute size for instance.
