### ISSUE TITLE
url/encode does not percent encode illegal characters

### ISSUE THREAD

**Issue by zackdever** [mpenet/spandex#29]
I have some documents with ids that have spaces in them (admittedly not ideal), which leads to this error when trying to perform a document get request:

```
java.net.URISyntaxException: Illegal character in path at index 22: /test-index/test-type/foo bar
java.lang.IllegalArgumentException: Illegal character in path at index 22: /test-index/test-type/foo bar
```

I'm getting around this by first calling `ring.util.codec/url-encode` on the id, so that `foo bar` becomes `foo%20bar`.

Both `clojurewerkz/elastisch` and the official Python client handle this and I wanted to know if there's any interest or plans to handle this within spandex? I don't imagine bringing in ring as a dep is warranted, but there may be a way to do it without adding a dep.

**Comment by zackdever** [comment]
Looking at this more, I realize the underlying low level HTTP client does not handle this, so it's perfectly fine for spandex to not support it, but since spandex is already to some degree doing url encoding by accepting a vector, it would be _nice_ to handle it here.

**Comment by mpenet** [comment]
Thanks for the report. Since we want to ease the work via urls as data I guess we might as well url-encode fragments. I will check what we can do without introducing a new dependency.

**Comment by mpenet** [comment]
I had to pull ring-codec in, I didn't find an url encoder that's both lightweight and not part of a giant library, this is something I might revisit, but for now that will do it.

It's on clojars as 0.5.5 fyi. 

Thanks again.

**Comment by zackdever** [comment]
That was super fast - thank you!
