### ISSUE TITLE
Knowing when bulk has imported successfully

### ISSUE THREAD

**Issue by jdkealy** [mpenet/spandex#32]
Hi, 

Great library! 

I'm using the bulk API and your tool to use it. 
I would think that calling 

`(async/<!! (:output-ch c))` 
would block until items had been imported into elastic search, however in my tests I'm: 

1. putting bulk items on channel
2. waiting for a respnose 
3. explicitly making an API call to refresh indices 

yet, the data is not available unless i put in a small delay, like 10 miliseconds between the blocking take step and the reindex step. 

Do you have any recommendations to make sure data is imported without setting an arbitrary timeout like above ?

**Comment by mpenet** [comment]
This is not really dependant on spandex, I guess you can play with index.refresh_interval to mitigate this or pass a `refresh` qs parameter to the bulk request map defaults (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html).
