### ISSUE TITLE
RequestConfig$Builder/setDecompressionEnabled is deprecated

### ISSUE THREAD

**Issue by rborer** [mpenet/spandex#35]
Hi,

I just noticed while browsing https://github.com/mpenet/spandex/blob/dbc1a4e897bff0f0ebfbb47eda3bd7dacce57d8b/src/clj/qbits/spandex/client_options.clj#L54 that the call to `.setDecompressionEnabled` is deprecated: https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html#setDecompressionEnabled(boolean)

It now modified the same variable than `.setContentCompressionEnabled`. Shall we simply remove `:decompression?` parameter?

**Comment by mpenet** [comment]
yep that sounds like a good idea. 
I was planning a cleanup once 7.x settles down but feel free to send a PR on this.
