### ISSUE TITLE
UnknownHostException :: invalid IPv6 address  

### ISSUE THREAD

**Issue by crankyadmin** [mpenet/spandex#39]
Hi, 

On OS X `10.13.4` using the below code: 

```clojure
(def state (atom {:config {}
                  :connection nil}))

(defn get-elasticsearch-config
  []
  {:host         (env :es-host)
   :port         (env :es-port)
   :cluster-name (env :es-cluster-name)})

(defn connect-to-elasticsearch!
  [{:keys [host port cluster-name]}]
  (let [conn (try
               (s/client {:hosts [(str "http://" host ":" port)]})
               (catch Exception e (debug (str (.getStackTrace e)))))]
    (swap! state assoc :connection conn)
    conn))

(defn get-connection!
  []
  (let [es-config (get-elasticsearch-config)]
    (if (:connection @state)
      (:connection @state)
      (try
        (connect-to-elasticsearch! (connect-to-elasticsearch! es-config))
        (catch Exception e (error "Exception thrown connecting to Elasticsearch, es-config: " (:config @state) (str (.getMessage e))))))))
```

When trying to do anything like `(s/request conn {:url [:things :thing] :method :put :body "foobar"})` causes it to throw `UnknownHostException :: invalid IPv6 address`. I think issue #38 is related. An underlaying libuary I think is preferring IPv6 which on Macs is still not greatly supported. As with the above mentioned issue, I can connect fine with `clj-http`. 

Thanks

**Comment by mpenet** [comment]
Can you share the values you're passing for host/port?

**Comment by mpenet** [comment]
You can also try to pass "-Djava.net.preferIPv4Stack=true" to jvm opts

**Comment by crankyadmin** [comment]
Host: `127.0.0.1`
Port: `9200`

Already tired passing `-Djava.net.preferIPv4Stack=true` and `-Djava.net.preferIPv6Addresses=false` from the ``jvm-opts` in lein. 

```  :jvm-opts ["-Djava.net.preferIPv4Stack=true" "-Djava.net.preferIPv6Addresses=false"]```

**Comment by mpenet** [comment]
Your code calls connect-to-elasticsearch! twice in a row btw

**Comment by crankyadmin** [comment]
Yes it does :( I've fixed that now.

**Comment by mpenet** [comment]
Does it fix the issue you had?

**Comment by crankyadmin** [comment]
Sadly not. Same `UnknownHostException :: invalid IPv6 address`.

**Comment by mpenet** [comment]
Too bad. I can't look into this before I am back from holidays tho, so that will have to wait a week.

**Comment by mpenet** [comment]
I can't test on osx, but on linux I can't reproduce the issue at all. Our tests also run with the same settings without a hitch. I'd suggest you look into osx specific problems related to networking and maybe try to make sure you actually get the right parameters from your env to the client.
I am going to close for now, but feel free to comment here if/when you figure it out.
