### ISSUE TITLE
how to connect using HTTPS?

### ISSUE THREAD

**Issue by faxm0dem** [mpenet/spandex#40]
I'm trying to connect to my searchguard enabled cluster using https.
However, I get:

```
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I understand I need to point spandex to the CA file, maybe by setting up a ssl-context?
Here's what I tried but which doesn't work:

```clojure
(:import
           (org.apache.hc.client5.http.ssl DefaultHostnameVerifier
                                           NoopHostnameVerifier
                                           SSLConnectionSocketFactory))

(connect {:ssl-context (javax.net.ssl SSLContext NoopHostnameVerifier/INSTANCE)
          :hosts ["https://node01:9200" "https://node42:9200"]
          :basic-auth {:user "spandex" password "xednaps"}})
```

**Comment by mpenet** [comment]
:ssl-context is also part of :http-client options: 

https://cljdoc.xyz/d/cc.qbits/spandex/0.6.4/api/qbits.spandex#client

**Comment by faxm0dem** [comment]
yes, but I have no idea on how to achieve this

**Comment by faxm0dem** [comment]
so apart from the :http-client I forgot, does the syntax seem sane to you?

**Comment by mpenet** [comment]
there is an example here: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html

Appart from the syntax I can't say, I haven't checked myself.

**Comment by faxm0dem** [comment]
I'll try, thanks. For now I imported the ca to the system's default truststore

**Comment by mpenet** [comment]
Let me know how it goes, this could be something interesting for #38 too.

**Comment by mpenet** [comment]
@faxm0dem any news on this?

**Comment by faxm0dem** [comment]
sorry, not yet: for now I imported the CA into the system's java keystore
