### ISSUE TITLE
`scroll-chan` doesn't use `scroll-id` from most recent request

### ISSUE THREAD

**Issue by firthh** [mpenet/spandex#44]
From the ElasticSearch [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html):
> The initial search request and each subsequent scroll request each return a _scroll_id. While the _scroll_id may change between requests, it doesn’t always change — in any case, only the most recently received _scroll_id should be used.

Reading through the code it looks like `scroll-chan` only uses the `scroll-id` from the first response rather than from the previous response for each scroll request

**Comment by mpenet** [comment]
Right, good catch. I will fix that tomorrow.

Thanks!

**Comment by firthh** [comment]
Amazing! Thanks for the quick turn around
