### ISSUE TITLE
ssl-context-trust-all doesn't seem to work

### ISSUE THREAD

**Issue by jdkealy** [mpenet/spandex#57]
Hi, 

I'm on an internal intranet and currently have an invalid cert. 

I try to connect via 

`(s/client {:hosts ["https:invalid-cert.com"] :ssl-context (client/ssl-context-trust-all)})`
(paraphrasing) 

And i get 
```PNIX path building failed:
unable to find valid certfication path
```

I try
```
(s/client {
:hosts ["https:invalid-cert.com"] 
:http-client {:ssl-context (client/ssl-context-trust-all)}})
```

and i get
"host name does not match the certificate provided by the peer"

Any advice?

**Comment by burinc** [comment]
@jdkealy Could you see if my PR will work with your use-cases?
Thanks
