### ISSUE TITLE
How to use bulk request without filling buffer?

### ISSUE THREAD

**Issue by kanwei** [mpenet/spandex#58]
Using the example but I'm getting

```Execution error (AssertionError) at clojure.core.async.impl.channels.ManyToManyChannel/put_BANG_ (channels.clj:152).
Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
```

My code:

```
(doseq [company companies]

      (async/put! input-ch {"index" {"_index" index-name "_id" (:id company)}})
      (async/put! input-ch company))
```

**Comment by mpenet** [comment]
It's not really a spandex issue, you are missusing core async: you should use blocking puts here, so >!!, this one will block until there's room in the chan buffer, so respecting backpressure, while put! is async and will use the pending put queue (unrelated to the buffer) on the channel that is indeed limited in size.
