### ISSUE TITLE
Spec for `bulk-chann` requires `::request`

### ISSUE THREAD

**Issue by Limess** [mpenet/spandex#59]
Currently the spec for `bulk-chan-options` requires `:qbits.spandex.spec/request`, which in turn requires the `url` key. This does not seem to be necessary in practice:

```clj
(comment
  (s/explain ::spandex-spec/bulk-chan-options {:flush-threhold 99}))
;; {:flush-threhold 99} - failed: (contains? % :url) spec: :qbits.spandex.spec/request
```

**Comment by mpenet** [comment]
Right. It used to be the case but not anymore. I ll patch this later today. Thanks for the report.
