### ISSUE TITLE
Is it possible to add blocking/back-pressure to bulk-import channel ? 

### ISSUE THREAD

**Issue by jdkealy** [mpenet/spandex#70]
Hi, 

I have 600k records and I need to regularly re-index, however the indexing job takes so much RAM that my server crashes. I presume it's because I'm storing tons of data in core.async's message buffers before it can offload and put in elasticsearch. Is there some way the bulk channel can block if the backpressure starts to build? Or is it already doing that and I'm misunderstanding something ?

**Comment by mpenet** [comment]
Hi, 

It's already doing that:
The `input-ch` returned by bulk-chan is unbuffered by default, so backpressure would be triggered

But I suspect you are using a non blocking put to the input-chan (like `put!`) or creating tons of go blocks and doing >! on that channel.

**Comment by mpenet** [comment]
Internally the input-ch is consumed and forwards message to the flush-ch which will trigger a bulk request once it reaches a certain size or if a delay expires, you could try to tweak these  (they are options to the bulk-chan fn : `:flush-interval` (defaults to 5000 (ms)) and `:flush-threshold` (300 entries).

**Comment by jdkealy** [comment]
Thank you
